services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: diesel_demo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Uncomment to enable application container
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./config.toml:/app/config.toml
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
